export const data = [
  {
    project_id: 1,
    resource: "LukeB2641",
    week_commencing: "2024-04-27",
    days: 3,
    grade: "SI3",
  },
  {
    project_id: 1,
    resource: "LukeB2641",
    week_commencing: "2024-04-27",
    days: 2,
    grade: "SI3",
  },
  {
    project_id: 1,
    resource: "SteveD2341",
    week_commencing: "2024-04-27",
    days: 5,
    grade: "SI5",
  },
  {
    project_id: 2,
    resource: "RhiannonM1234",
    week_commencing: "2024-04-27",
    days: 3,
    grade: "SI3",
  },
  {
    project_id: 2,
    resource: "LukeB2641",
    week_commencing: "2024-04-27",
    days: 2,
    grade: "SI3",
  },
  {
    project_id: 3,
    resource: "LukeB2641",
    week_commencing: "2024-05-04",
    days: 3,
    grade: "SI3",
  },
  {
    project_id: 3,
    resource: "LukeB2641",
    week_commencing: "2024-05-04",
    days: 2,
    grade: "SI3",
  },
  {
    project_id: 3,
    resource: "SteveD2341",
    week_commencing: "2024-05-04",
    days: 5,
    grade: "SI5",
  },
  {
    project_id: 4,
    resource: "RhiannonM1234",
    week_commencing: "2024-05-04",
    days: 3,
    grade: "SI3",
  },
  {
    project_id: 1,
    resource: "LukeB2641",
    week_commencing: "2024-05-04",
    days: 2,
    grade: "SI3",
  },
];

export const months = [
  "Apr 2024",
  "May 2024",
  "Jun 2024",
  "Jul 2024",
  "Aug 2024",
  "Sep 2024",
  "Oct 2024",
  "Nov 2024",
  "Dec 2024",
  "Jan 2025",
  "Feb 2025",
  "Mar 2025",
];

export const project_details = [
  {
    id: 1,
    slug: "project-1",
    title: "Project 1",
    delivery_manager: "Luke Barnett",
    project_manager: "Curtis Freer",
    delivery_stream: "New York",
    value_stream: "Broadway",
    scrum_master: "Blobby",
    project_type: "TM",
    last_updated: new Date(2024, 3, 12, 4, 23, 0),
    line_of_business: "Project",
    task: "A40012345",
  },
  {
    id: 2,
    slug: "project-2",
    title: "Project 2",
    delivery_manager: "Luke Barnett",
    project_manager: "Curtis Freer",
    delivery_stream: "New York",
    value_stream: "Broadway",
    scrum_master: "Barney",
    project_type: "TM",
    last_updated: new Date(2024, 3, 11, 4, 23, 0),
    line_of_business: "Project",
    task: "A40012345",
  },
  {
    id: 3,
    slug: "project-3",
    title: "Project 3",
    delivery_manager: "Rhiannon Matthews",
    project_manager: "Curtis Freer",
    delivery_stream: "New York",
    value_stream: "Broadway",
    scrum_master: "Kermit",
    project_type: "FP",
    last_updated: new Date(2024, 3, 11, 4, 23, 0),
    line_of_business: "Project",
    task: "A40012345",
  },
  {
    id: 4,
    slug: "project-4",
    title: "Project 4",
    delivery_manager: "Rhiannon Matthews",
    project_manager: "Curtis Freer",
    delivery_stream: "New York",
    value_stream: "Far Far Away",
    scrum_master: "Lord Farquaad",
    project_type: "FP",
    last_updated: new Date(2024, 3, 11, 4, 23, 0),
    line_of_business: "Project",
    task: "A40012345",
  },
];
